### ISSUE TITLE
Service crashes

### ISSUE THREAD

**Issue by nmashni** [dequelabs/Deque-University-for-Android#34] opened 2018-10-04 12:57 UTC
The attest app crashed a lot of time on the android device used.

**Comment by chriscm2006** [comment] 2018-10-04 14:10
Stack trace/crash log or it didn't happen. We need to know device version, OS version, any other services that are running along with our service, the Automation framework being used.

We can't take action on this sentence alone. No combinations of the above that we test on create any known crashes. The most likely culprit is the automation framework. Automation frameworks take advantage of the Accessibility layer to do their work. Any other comments I provide on this are purely speculative. Need more information.

**Comment by chriscm2006** [comment] 2018-11-01 14:19
@nmashni Closing this. Happy to reopen if we get more details/evidence that it is caused by Attest and not the device or other framework.

**Closed by chriscm2006** 2018-11-01 14:19 UTC
Labels: Attest, Incomplete, Service
